#!/usr/bin/env python3
"""Generate docs/configuration/settings-reference.md from Poweradmin's settings.defaults.php.

Parses the file textually rather than executing it: the descriptions and the
"(added in X.Y.Z)" markers live in the trailing comments, which a require() would
discard. Keeps the docs build free of any PHP dependency.
"""
import argparse
import re
import sys
from pathlib import Path

KEY_RE = re.compile(r"^\s*'([^']+)'\s*=>\s*(.*?)\s*$")
ADDED_RE = re.compile(r"\(added in ([0-9]+\.[0-9]+\.[0-9]+)\)", re.I)


def parse(text):
    """Yield (path, default, description, added) for every leaf setting."""
    stack, rows = [], []
    in_block_comment = False

    for raw in text.split("\n"):
        stripped = raw.strip()

        # Skip docblocks; they describe groups, not individual keys.
        if in_block_comment:
            if "*/" in stripped:
                in_block_comment = False
            continue
        if stripped.startswith("/*"):
            in_block_comment = "*/" not in stripped
            continue
        if stripped.startswith("//") or not stripped:
            continue

        code, comment = split_value_and_comment(raw)
        code = code or ""

        m = KEY_RE.match(code)
        if m:
            key, rest = m.group(1), m.group(2).strip()
            # A value whose brackets close on the same line is a leaf, even when
            # it is a list: only a bracket left open starts a new section.
            if rest.startswith("[") and bracket_delta(rest) > 0:
                # Remember where this section started so an array whose entries are
                # all commented out still yields a row for the key itself.
                stack.append((key, len(rows), comment))
                continue
            value = rest.rstrip(",").strip()
            if not value:
                continue
            added = ADDED_RE.search(comment)
            description = ADDED_RE.sub("", comment).strip(" .-") if comment else ""
            rows.append((
                ".".join([f[0] for f in stack] + [key]),
                value,
                description,
                added.group(1) if added else "",
            ))
            continue

        # Any line that only closes brackets pops that many sections.
        delta = bracket_delta(code)
        for _ in range(-delta if delta < 0 else 0):
            if not stack:
                continue
            key, mark, opening_comment = stack.pop()
            if len(rows) == mark:
                added = ADDED_RE.search(opening_comment)
                rows.append((
                    ".".join([f[0] for f in stack] + [key]),
                    "[]",
                    ADDED_RE.sub("", opening_comment).strip(" .-"),
                    added.group(1) if added else "",
                ))
    return rows


def bracket_delta(code):
    """Net [ minus ] in code, ignoring anything inside quotes."""
    depth, quote, i = 0, None, 0
    while i < len(code):
        ch = code[i]
        if quote:
            if ch == "\\":
                i += 2
                continue
            if ch == quote:
                quote = None
        elif ch in "'\"":
            quote = ch
        elif ch == "[":
            depth += 1
        elif ch == "]":
            depth -= 1
        i += 1
    return depth


def split_value_and_comment(rest):
    """Split a line into (code, trailing comment), respecting quotes."""
    out, quote, i = [], None, 0
    while i < len(rest):
        ch = rest[i]
        if quote:
            if ch == "\\" and i + 1 < len(rest):
                out.append(rest[i:i + 2]); i += 2; continue
            if ch == quote:
                quote = None
            out.append(ch)
        elif ch in "'\"":
            quote = ch
            out.append(ch)
        elif rest.startswith("//", i):
            return "".join(out), rest[i + 2:].strip()
        else:
            out.append(ch)
        i += 1
    return "".join(out), ""


def render(rows, source_version):
    by_section = {}
    for path, value, description, added in rows:
        by_section.setdefault(path.split(".")[0], []).append((path, value, description, added))

    out = [
        "<!-- Generated by scripts/gen_settings_reference.py from config/settings.defaults.php.",
        "     Do not edit by hand; run the script instead. -->",
        "",
        "# Settings Reference",
        "",
        f"Every setting in `config/settings.defaults.php` as of Poweradmin {source_version}, with its",
        "shipped default. This page is generated from the source file, so it is complete by",
        "construction - but it is an index, not an explanation. The pages under **Configuration**",
        "describe what these settings actually do and when to change them.",
        "",
        "Override any of them in `config/settings.php`; see [Basic Configuration](basic.md).",
        "",
    ]
    for section in sorted(by_section):
        out += [f"## {section}", "", "| Setting | Default | Description | Added in |",
                "|---|---|---|---|"]
        for path, value, description, added in by_section[section]:
            anchor = "setting-" + path.replace(".", "-").replace("_", "-")
            out.append(
                f"| `{path}` {{#{anchor}}} | {code_cell(value)} | {text_cell(description) or '-'} "
                f"| {added or '-'} |"
            )
        out.append("")
    return "\n".join(out)


def code_cell(text):
    r"""Render a value as inline code inside a table cell.

    A `\|` escape leaves a visible backslash inside a code span, and `&#124;`
    inside backticks is double-escaped. Raw <code> with the entity is the only
    form that renders as a literal pipe (md_in_html is enabled in mkdocs.yml).
    """
    if "|" not in text:
        return f"`{text}`"
    escaped = (text.replace("&", "&amp;").replace("<", "&lt;")
                   .replace(">", "&gt;").replace("|", "&#124;"))
    return f"<code>{escaped}</code>"


def text_cell(text):
    return text.replace("|", "&#124;")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--settings", required=True, type=Path)
    ap.add_argument("--version", default="")
    ap.add_argument("--out", type=Path)
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if --out is missing or stale instead of writing it")
    args = ap.parse_args()

    rows = parse(args.settings.read_text())
    if not rows:
        sys.exit("no settings parsed - the source layout probably changed")
    body = render(rows, args.version)

    if args.check:
        if not args.out.exists() or args.out.read_text() != body:
            sys.exit(f"{args.out} is out of date; regenerate with scripts/gen_settings_reference.py")
        print(f"{args.out} is up to date ({len(rows)} settings)")
        return
    args.out.write_text(body)
    print(f"wrote {args.out} ({len(rows)} settings)")


if __name__ == "__main__":
    main()
